server:
  port: 8070

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/sisgr-realm

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOrigins:
              - "http://localhost:5173"
              - "http://localhost:8070"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: customer
          uri: lb://customer-service
          predicates:
            - Path=/api/customers/**
        - id: inventory
          uri: lb://inventory-service
          predicates:
            - Path=/api/tools/**
        - id: loan
          uri: lb://loan-service
          predicates:
            - Path=/api/loans/**
        - id: kardex
          uri: lb://kardex-service
          predicates:
            - Path=/api/kardex/**
        - id: pricing
          uri: lb://pricing-service
          predicates:
            - Path=/api/pricing/**
        - id: reporting
          uri: lb://reporting-service
          predicates:
            - Path=/api/reports/**
        - id: user
          uri: lb://user-service
          predicates:
            - Path=/api/users/**
