server:
  port: 0  # puerto aleatorio (cumple con "no asignación de puertos")

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/customerms
    username: postgres
    password: "ambar2004"

  jpa:
    hibernate:
      ddl-auto: update   # crea/actualiza tablas automáticamente
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka/