server:
  port: 0  # puerto aleatorio (cumple con "no asignación de puertos")

spring:
  application:
    name: loan-service

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/loanms
    username: postgres
    password: "ambar2004"

  jpa:
    hibernate:
      ddl-auto: update   # crea/actualiza tablas automáticamente
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

eureka:
  instance:
    preferIpAddress: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  services:
    inventory:
      base-url: ${INVENTORY_URL:http://inventory-service}
    pricing:
      base-url: ${PRICING_URL:http://pricing-service}
    customer:
      base-url: ${CUSTOMER_URL:http://customer-service}
