spring.application.name=eureka-server
server.port=8761
spring.config.import=optional:configserver:http://localhost:8888
# Indispensable para servidor único (evita el error del cliente)
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Opcional pero recomendado para evitar logs de error de conexión
eureka.server.waitTimeInMsWhenSyncEmpty=0